## YAML Template.
---
nextReportId: 2
reports:
    1:
        playerName: Islid
        warningPoints: 3
        reason: "Requested a plugin ;)"
        reporterName: Drazisil
        reportDate: 2012/05/01