## YAML Template.
---
nextReportId: 2
reports:
    1:
        playerName: Drazisil
        warningPoints: 0
        reason: Testing...
        reporterName: Drazisil
        reportDate: 2012/05/01
        active: true
