#
# NerdReportCard's configuration file
#
# About editing this file:
# - DO NOT USE TABS. You MUST use spaces or Bukkit will complain. If
# - Don't get rid of the indents - these are intentional.
# - If you want to check the format of this file before running with it,
#   paste it into http://yaml-online-parser.appspot.com/
#   and see if it gives "ERROR:".
# - Lines starting with # are comments and are ignored.
#

database:
    sql:
        use: false
        address: localhost
        port: 3306
        username: user
        password: password
        dbname: nerdrc
        prefix: nrc_
    yamlfile: reports.yml
debug: false
